version: '3.5'
services:
  postgres:
    restart: always
    container_name: 'postgres'
    hostname: postgres
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=checkorders
      - POSTGRES_PASSWORD=checkorders
      - POSTGRES_DB=checkorders

  checkorders:
    build: .
    container_name: 'checkorders'
    depends_on:
      - postgres
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    stdin_open: true

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres