"""password added

Revision ID: ef6e7a5d832d
Revises: b53dcb864099
Create Date: 2021-01-15 19:10:14.935336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6e7a5d832d'
down_revision = 'b53dcb864099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
